name: genshingameinfo
description: genshin game info from mihoyo bbs
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed: ^2.0.3
  dio: ^4.0.4
  crypto: ^3.0.1
  json_annotation: ^4.5.0

dev_dependencies:
  dependency_validator: ^3.0.0
  build_runner: ^2.1.5
  test: ^1.20.1
  json_serializable: ^6.0.1
  freezed: ^2.0.3+1

