name: genshintoolsapp
description: genshin tools app
publish_to: 'none'
version: 2.7.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  freezed: ^2.0.3
  dio: ^4.0.4
  flutter_markdown: ^0.6.8
  flutter_bloc: ^8.0.0
  provider: ^6.0.2
  hydrated_bloc: ^9.0.0-dev.2
  path_provider: ^2.0.7
  expandable: ^5.0.1
  flutter_services_binding: ^0.1.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.17
  package_info_plus: ^1.3.0
  webview_flutter: ^3.0.0
  flutter_hooks: ^0.18.1
  rxdart: ^0.27.3
  genshingameinfo: ^1.0.0
  genshindb: ^2.7.0
  freearch:  ^1.0.0
  webdav:  ^1.0.0

dev_dependencies:
  dependency_validator: ^3.0.0
  build_runner: ^2.1.5
  test: ^1.20.1
  json_serializable: ^6.0.1
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/genshindb/
