name: genshindb
description: genshindb
version: 2.7.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3

dev_dependencies:
  dependency_validator: ^3.0.0
  build_runner: ^2.1.5
  test: ^1.20.1
  json_serializable: ^6.0.1
  freezed: ^2.0.3+1
