name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: "^17"
      - uses: pnpm/action-setup@v2
        with:
          version: "^6"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: make bootstrap.all
      - run: make convert
      - run: make gen build.android

      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          folder: ./packages/genshintoolsapp/build/.release
          branch: release-stable
          single-commit: true
