name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: "^17"
      - uses: pnpm/action-setup@v2
        with:
          version: "^6"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: make install
      - run: make convert
      - run: make build.android

      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: release-stable
          FOLDER: ./build/.release
          CLEAN: true